# Generated by Django 2.2 on 2021-06-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_comment_wall_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='wall_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='login_app.Wall_Message'),
        ),
    ]
