# Generated by Django 2.2 on 2021-06-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210616_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wall_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='login_app.Wall_Message'),
        ),
    ]
